// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetcsSchool_Api.Data;

namespace ProjetcsSchool_Api.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("ProjetcsSchool_Api.models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataNascimento = "11/04/1998",
                            Nome = "Lucas",
                            ProfessorId = 1,
                            Sobrenome = ""
                        },
                        new
                        {
                            Id = 2,
                            DataNascimento = "05/03/1997",
                            Nome = "Jhonatan",
                            ProfessorId = 1,
                            Sobrenome = ""
                        },
                        new
                        {
                            Id = 3,
                            DataNascimento = "23/02/2001",
                            Nome = "Alan",
                            ProfessorId = 2,
                            Sobrenome = "Juan"
                        });
                });

            modelBuilder.Entity("ProjetcsSchool_Api.models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Professores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Àlex"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Eduardo"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "David"
                        });
                });

            modelBuilder.Entity("ProjetcsSchool_Api.models.Aluno", b =>
                {
                    b.HasOne("ProjetcsSchool_Api.models.Professor", "Professor")
                        .WithMany("Alunos")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("ProjetcsSchool_Api.models.Professor", b =>
                {
                    b.Navigation("Alunos");
                });
#pragma warning restore 612, 618
        }
    }
}
